name: On PR Open
on:
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/azuredatastudio'
          ref: main
          path: ./actions
          set-safe-directory: false
      - name: Install Actions
        run: npm install --production --prefix ./actions/build/actions
